name: Backend Testing
on:
  push:
    branches: [fullStack-1]

env:
  DB_USER: backend_db
  DB_PASSWORD: bi1fUbaMAHZk9WXz
  DB_NAME: testDB
  TOKEN_SCERT: thisSecretIsNotASecret
  SERVER_PORT: 5000
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        
      - name: Install backend 
        working-directory: ./backend
        run: npm install
     
      - name: Backend tests 
        working-directory: ./backend
        run: npm test
