name: Backend Testing

on: 
  [workflow_dispatch]
  push:
    paths: ['backend/**']

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Backend Testing
      run: | 
        cd backend
        npm ci
        npm test