name: Backend Testing
on:
  push:
    paths: ['backend/**']
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install backend 
        working-directory: ./backend
        run: npm install
     
      - name: Backend tests 
        working-directory: ./backend
        run: npm test
