name: Backend Testing
on:
  push:
    branches: [fullStack-1]
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        
      - name: Install backend 
        working-directory: ./backend
        run: npm install
     
      - name: Backend tests 
        working-directory: ./backend
        run: npm test
