name: Backend Testing
on:
  push:
    paths: ['backend/**']
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Backend
      - working-directory: ./backend
        run: |
          npm install
          npm test
