name: Backend Testing
on:
  push:
    paths: ['backend/**']
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Backend
        run: |
          cd backend
          npm ci
          npm test