name: Backend Testing
on:
  pull_request:
  push:
    paths: ['backend/**']
  
env:
  DB_USER: backend_db
  DB_PASSWORD: bi1fUbaMAHZk9WXz
  DB_NAME: testDB
  TOKEN_SCERT: thisSecretIsNotASecret
  SERVER_PORT: 5000
  
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
        
      - name: Build Backend 
        run: |
          cd backend
          npm ci
          npm run build --if-present
          
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Test Backend  
        run: |
          cd backend
          npm ci
          npm test
