name: Build and Publish Docker Image

on:
  [workflow_dispatch]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      - uses: actions/checkout@v2

      - name: Docker Buildx Set Up
      - id: buildx
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build And Push Docker Images
      - uses: docker/build-push-action@v2
        with:
          context: ./backend
          tags: sammulto/dogdates:BackendFromGit

      - name: Action Result
      - run: echo ${{ steps.docker_build.outputs.digest }}
