name: docker

on:
  push:
    branches:
      - 'fullStack'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Docker Buildx Set Up
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build And Push Docker Images
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: sammulto/dogdates:backend-git
      - 
        name: Result
        run: echo ${{ steps.docker_build.outputs.digest }}
        
