name: Frontend Build

on: 
  push:
    paths: ['frontend/**']

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Frontend Build
      run: | 
        cd frontend
        npm ci
        npm run build