name: Frontend Testing
on:
  push:
    paths: ['frontend/**']
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Frontend
        run: |
          cd frontend
          npm ci
          npm run build
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Test frontend
  #       run: |
  #         cd frontend
  #         npm ci
  #         npm test
