name: FullStack Branch Backend CI

on: 
  [workflow_dispatch]
#  push:
#    branches: [ fullStack ]
#    paths: ['backend/**']
#  pull_request:
#    branches: [ fullStack ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Back End CI
      run: | 
        cd backend
        npm ci
        npm run build --if-present
#    - run: npm test
