name: Manual Dispatch Tests

on: 
  [workflow_dispatch]

env:
  DB_USER: backend_db
  DB_PASSWORD: bi1fUbaMAHZk9WXz
  DB_NAME: testDB
  TOKEN_SCERT: thisSecretIsNotASecret
  SERVER_PORT: 5000
  
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Frontend
      run: | 
        cd frontend
        npm ci
        npm run build
        
  # test-frontend:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Test Frontend
  #     run: | 
  #       cd frontend
  #       npm ci
  #       npm test
        
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Backend
      run: | 
        cd backend
        npm install
        npm test
